@echo off
setlocal EnableExtensions
REM ============================================================
REM  CONTROLLER-SIDE tool: build a personalized installer folder
REM  for ONE target PC. The target person only double-clicks ONE
REM  file and clicks Yes on up to TWO admin prompts - no account,
REM  no signup, no e-mail, nothing to copy.
REM
REM  How the "three lines" become automatic:
REM    PORT  -> fixed 8808, baked into the generated installer
REM    KEY   -> generated HERE, baked into the generated installer
REM    IP    -> the target joins YOUR tailnet with YOUR auth key,
REM             so "tailscale status" on this PC shows it instantly
REM
REM  Usage:
REM    make_target_installer.bat <nickname> <tailscale-auth-key>
REM    (missing args are prompted)
REM
REM  Auth key: create a SINGLE-USE key at
REM    https://login.tailscale.com/admin/settings/keys
REM
REM  Output:
REM    target-<nickname>\            <- send this WHOLE folder
REM    my-targets\<nickname>.env     <- secrets stay on THIS pc
REM ============================================================

set "NAME=%~1"
if "%NAME%"=="" set /p "NAME=Target nickname (letters/digits/_/-, e.g. uncle-pc): "
if "%NAME%"=="" (echo [ERROR] nickname required & pause & exit /b 1)
echo %NAME%| findstr /r "^[a-zA-Z0-9_-][a-zA-Z0-9_-]*$" >nul
if errorlevel 1 (echo [ERROR] nickname: letters/digits/_/- only & pause & exit /b 1)

set "TSKEY=%~2"
if "%TSKEY%"=="" set /p "TSKEY=Paste the Tailscale AUTH KEY (single-use): "
if "%TSKEY%"=="" (
    echo [ERROR] auth key required - generate one at:
    echo   https://login.tailscale.com/admin/settings/keys
    pause
    exit /b 1
)

set "PORT=8808"
for /f %%i in ('powershell -NoProfile -Command "[guid]::NewGuid().ToString('N')"') do set "BEARER=%%i"

set "OUTDIR=%~dp0target-%NAME%"
if not exist "%OUTDIR%" mkdir "%OUTDIR%"
if not exist "%~dp0my-targets" mkdir "%~dp0my-targets"
copy /y "%~dp0install_windows_mcp.bat" "%OUTDIR%" >nul
if exist "%~dp0windows-mcp-server.exe" copy /y "%~dp0windows-mcp-server.exe" "%OUTDIR%" >nul
if exist "%~dp0dist\windows-mcp-server.exe" copy /y "%~dp0dist\windows-mcp-server.exe" "%OUTDIR%" >nul

> "%OUTDIR%\install_on_target.bat" echo @echo off
>> "%OUTDIR%\install_on_target.bat" echo rem One-click installer generated by make_target_installer.bat
>> "%OUTDIR%\install_on_target.bat" echo rem All settings are baked in - nothing to type or copy.
>> "%OUTDIR%\install_on_target.bat" echo call "%%~dp0install_windows_mcp.bat" %PORT% %BEARER% %TSKEY%

> "%~dp0my-targets\%NAME%.env" echo PORT=%PORT%
>> "%~dp0my-targets\%NAME%.env" echo BEARER=%BEARER%
>> "%~dp0my-targets\%NAME%.env" echo TSKEY=%TSKEY%
>> "%~dp0my-targets\%NAME%.env" echo CREATED=%DATE% %TIME%

echo.
echo ============================================================
echo  Ready! Send the WHOLE folder to the target person:
echo    %OUTDIR%
echo  (WeChat / cloud drive / USB - all fine)
echo.
echo  Target person does ONLY this:
echo    1. double-click install_on_target.bat
echo    2. click Yes on up to TWO admin prompts
echo       (Tailscale install + firewall rule)
echo  No account, no signup, nothing to type or copy.
echo.
echo  Meanwhile, start waiting on THIS pc:
echo    connect_target.bat %NAME%
echo  It auto-detects the new device in your tailnet and
echo  verifies the connection, then prints the MCP config.
echo ============================================================
pause
